name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Upload Static Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Set outputs
        id: vars
        run: | 
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "username=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT
      - name: Deploy to gh-pages branch
        run: |
          npm install -g gh-pages
          GITHUB_REPO_WITH_TOKEN=$(echo ${GITHUB_REPO_LINK} | sed "s/\/\//\/\/git:${GITHUB_TOKEN}@/g")
          gh-pages -d build \
                    -o origin \
                    -m "deploy: ${COMMIT}" \
                    -u "${AUTHOR_USER} <${AUTHOR_EMAIL}>" \
                    -r ${GITHUB_REPO_WITH_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR_USER: ${{ steps.vars.outputs.username }}
          AUTHOR_EMAIL: ${{ steps.vars.outputs.email }}
          COMMIT: ${{ steps.vars.outputs.sha_short }}
          GITHUB_REPO_LINK: "${{ github.server_url }}/${{ github.repository }}.git"